language: python
python:
  - "2.7"
  - "2.6"
install:
  - sudo apt-get install zlib1g-dev
  - sudo ln -s /usr/lib/i386-linux-gnu/libz.so /usr/lib
  - python setup.py install
script:
  - python setup.py tests
